[profile.dev]
incremental = true

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"

[profile.tiny]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1

[profile.fast]
inherits = "release"
lto = true
codegen-units = 1

[build]
rustflags = ["-Ctarget-cpu=native"]